### PR TITLE
Add german umlaute

### PR DESCRIPTION
**Pull request by stheine**
Hi, I needed the german umlaute in the oled fonts, so I added them to your tool. Would be great if you would merge that.

Regards
  Stefan

### CODE REVIEW

**Comment by noopkat** [comment]
Hey @stheine thanks for adding these characters 🇩🇪 

Before I merge this, would you mind please removing the `_config.yml` file from the PR?
Thanks and sorry for the delay in reviewing this code 🙇‍♀️

**Comment by stheine** [comment]
thanks for looking at it. done as requested.

**Comment by noopkat** [comment]
thank you again! I can't believe this is from July, I am so sorry! 

image

**Comment by stheine** [comment]
Hi @noopkat ,

thanks for the merge.

I wonder how active this and the related https://github.com/noopkat/oled-js is with you?
I'm asking, since I forked oled-js and adapted it for SH1106 (similar but not same to SSD1306). in this context I found number of issues in that lib and the font-foundry.

most important one: https://github.com/stheine/oled-js-font-foundry/commit/1808bbcb54a84a386d1c4cba9332b6bb7ee9b1c3
that causes large characters being truncated (generate a consolas-16 font and display the lower case 'g', watch the bottom right portion of the descender).
but if you fix that, you'll have to also fix the unpacking of the font in oled-js, making it a breaking change, requiring updates to both, the lib and generated fonts.
https://github.com/stheine/sh1106-js/commit/26ba891bc59b13788794e8f1502ddc0589b87e97#diff-165a0e1118c92b867abcc97a362642dfR199

just listing some other changes I did:
- change to async/await. switched from i2c to rpio (since i2c doesn't work on node 10 https://github.com/kelly/node-i2c/issues/90)
- remove irrelevant code (irrelevant for me!)

- change the API for writeString() (drop setCursor(), add position directly into writeString(), drop ability to change font size, drop wrapping)
- change the API for _drawChar() (drop setCursor())
- prevent writeString to write outside the display area
all in https://github.com/stheine/sh1106-js/commit/26ba891bc59b13788794e8f1502ddc0589b87e97

- prevent drawPixel to draw outside the display area
https://github.com/stheine/sh1106-js/commit/43b4b2ac288887b9459ae2eb7b1f302c70e32639#diff-165a0e1118c92b867abcc97a362642dfR392
https://github.com/stheine/sh1106-js/commit/26ba891bc59b13788794e8f1502ddc0589b87e97#diff-165a0e1118c92b867abcc97a362642dfR312

- added API for dashed lines and dashed rectangles
https://github.com/stheine/sh1106-js/commit/3c6120b948c28b6219ec7d9fe2cfabe78b55ee07

I don't know if you want to take over code back into your lib. it's not easy to create PRs as the code has diverged that much. but let me know if I can help.


Regards
  Stefan

**Comment by noopkat** [comment]
thanks for summarising this for me! Oled-js is still an active project and I'm currently rewriting this library from scratch and it would be really helpful for me to use some of these bug fixes especially.
At this point, until the library is refactored and complete, I won't be adding support for SH1106 just yet. I also want to add support for controller SSD1322, but again rewriting the library to support multiple controllers would be necessary first.

I'm curious about the changes needed for the Raspberry Pi. Given that Oled-js leverages Johnny Five to work, theoretically you can use the [Raspi IO plugin](https://github.com/nebrius/raspi-io) with Johnny Five and it *should* work out of the box. I'll test this soon to make sure I'm not eating my words, but this was why I wrote Oled-js the way that I did, so that it had maximum compatibility with as many boards as possible.

**Comment by stheine** [comment]
I failed to get it running with Johnny Five, but I don't remember 
exactly why... it might even be that it would have worked ok, but the 
issues had been causes by the different controller (SH1106 vs SSD1306), 
so I had various troubles until I finally got the display under control 
and tested various things in between. in the end I switched to 
https://www.npmjs.com/package/rpio because that gave me a simple and 
working access to i2c.

if you rewrite this, there's one thing I would recommend: try to split 
the controller specifics from the higher-level graphing functions. in 
the end, the only functions that actually access the controller are 
_drawPixel() and update().
so I would split the lower level code (connect controller, init, draw 
pixel, update) that needs to be (at least somewhat) controller specific, 
from the higher level code (drawLine, drawRect, writeString, etc) that 
come down to drawPixel() in the end.
and maybe you can even make that two modules, so that there are multiple 
of the lower level - one per controller - that each expose an init() and 
a drawPixel() and not a lot more. and another module for the high level 
graphing code.

and if you want your lib to control multiple controllers you need to 
have access to all of them for testing in parallel - that's why I 
stripped out all the support for SSD1306, as I had to test out so many 
things until I got SH1106 under control, that I couldn't be sure that 
SSD 1306 would still work - and I didn't have one for testing.

**Pull request merged**
